
package com.sharifpro.matma.wscall.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "User", targetNamespace = "http://com.sharifpro.matma.wscall.user")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface User {


    /**
     * 
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProfileReturn", targetNamespace = "http://com.sharifpro.matma.wscall.user", partName = "getProfileReturn")
    public String getProfile(
        @WebParam(name = "userName", targetNamespace = "http://com.sharifpro.matma.wscall.user", partName = "userName")
        String userName);

    /**
     * 
     * @param profile
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "updateProfileReturn", targetNamespace = "http://com.sharifpro.matma.wscall.user", partName = "updateProfileReturn")
    public boolean updateProfile(
        @WebParam(name = "profile", targetNamespace = "http://com.sharifpro.matma.wscall.user", partName = "profile")
        Profile profile);

}
