package com.sharifpro.eurb.info;

import java.util.Arrays;
import java.util.List;

/**
 * All Authorities in our system
 * 
 * @author Mohammad Dashti (m_dashti [at] ce.sharif.edu)
 */
public class AuthorityType {

	public final static String POSTFIX_ACTION_VIEW_LIST = "_L";
	public final static String POSTFIX_ACTION_VIEW = "_R";
	public final static String POSTFIX_ACTION_EDIT = "_W";
	public final static String POSTFIX_ACTION_CREATE = "_C";
	public final static String POSTFIX_ACTION_DELETE = "_D";
	public final static String POSTFIX_ACTION_SHARING = "_S";
	public final static String POSTFIX_ACTION_EXECUTE = "_E";
	
	public final static String PREFIX_ROLE = "ROLE_";
	
	public final static String USER = PREFIX_ROLE + "USER";
	public final static String ADMIN = PREFIX_ROLE + "ADMIN";
	
	//BASE MENU
	public final static String BASE_MANAGEMENT_MENU = "BMM";
	public final static String ROLE_BASE_MANAGEMENT_MENU_VIEW = PREFIX_ROLE + BASE_MANAGEMENT_MENU + POSTFIX_ACTION_VIEW;
	
	public final static String BASE_DB_CONFIG = "DBM";
	public final static String ROLE_BASE_DB_CONFIG_VIEW_LIST = PREFIX_ROLE + BASE_DB_CONFIG + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_BASE_DB_CONFIG_VIEW = PREFIX_ROLE + BASE_DB_CONFIG + POSTFIX_ACTION_VIEW;
	public final static String ROLE_BASE_DB_CONFIG_EDIT = PREFIX_ROLE + BASE_DB_CONFIG + POSTFIX_ACTION_EDIT;
	public final static String ROLE_BASE_DB_CONFIG_CREATE = PREFIX_ROLE + BASE_DB_CONFIG + POSTFIX_ACTION_CREATE;
	public final static String ROLE_BASE_DB_CONFIG_DELETE = PREFIX_ROLE + BASE_DB_CONFIG + POSTFIX_ACTION_DELETE;
	public final static String ROLE_BASE_DB_CONFIG_SHARING = PREFIX_ROLE + BASE_DB_CONFIG + POSTFIX_ACTION_SHARING;
	
	public final static String BASE_TABLE_MAPPING = "TM";
	public final static String ROLE_BASE_TABLE_MAPPING_VIEW_LIST = PREFIX_ROLE + BASE_TABLE_MAPPING + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_BASE_TABLE_MAPPING_VIEW = PREFIX_ROLE + BASE_TABLE_MAPPING + POSTFIX_ACTION_VIEW;
	public final static String ROLE_BASE_TABLE_MAPPING_EDIT = PREFIX_ROLE + BASE_TABLE_MAPPING + POSTFIX_ACTION_EDIT;
	public final static String ROLE_BASE_TABLE_MAPPING_CREATE = PREFIX_ROLE + BASE_TABLE_MAPPING + POSTFIX_ACTION_CREATE;
	public final static String ROLE_BASE_TABLE_MAPPING_SHARING = PREFIX_ROLE + BASE_TABLE_MAPPING + POSTFIX_ACTION_SHARING;
	
	public final static String BASE_COL_MAPPING = "CM";
	public final static String ROLE_BASE_COL_MAPPING_VIEW_LIST = PREFIX_ROLE + BASE_COL_MAPPING + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_BASE_COL_MAPPING_VIEW = PREFIX_ROLE + BASE_COL_MAPPING + POSTFIX_ACTION_VIEW;
	public final static String ROLE_BASE_COL_MAPPING_EDIT = PREFIX_ROLE + BASE_COL_MAPPING + POSTFIX_ACTION_EDIT;
	public final static String ROLE_BASE_COL_MAPPING_CREATE = PREFIX_ROLE + BASE_COL_MAPPING + POSTFIX_ACTION_CREATE;
	public final static String ROLE_BASE_COL_MAPPING_SHARING = PREFIX_ROLE + BASE_COL_MAPPING + POSTFIX_ACTION_SHARING;
	
	//SECURITY MENU
	public final static String SECURITY_MANAGEMENT_MENU = "SMM";
	public final static String ROLE_SECURITY_MANAGEMENT_MENU_VIEW = PREFIX_ROLE + SECURITY_MANAGEMENT_MENU + POSTFIX_ACTION_VIEW;
	
	public final static String SEC_USER_MANAGEMENT = "UM";
	public final static String ROLE_SEC_USER_MANAGEMENT_VIEW_LIST = PREFIX_ROLE + SEC_USER_MANAGEMENT + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_SEC_USER_MANAGEMENT_VIEW = PREFIX_ROLE + SEC_USER_MANAGEMENT + POSTFIX_ACTION_VIEW;
	public final static String ROLE_SEC_USER_MANAGEMENT_EDIT = PREFIX_ROLE + SEC_USER_MANAGEMENT + POSTFIX_ACTION_EDIT;
	public final static String ROLE_SEC_USER_MANAGEMENT_CREATE = PREFIX_ROLE + SEC_USER_MANAGEMENT + POSTFIX_ACTION_CREATE;
	public final static String ROLE_SEC_USER_MANAGEMENT_DELETE = PREFIX_ROLE + SEC_USER_MANAGEMENT + POSTFIX_ACTION_DELETE;
	
	public final static String SEC_GROUP_MANAGEMENT = "GM";
	public final static String ROLE_SEC_GROUP_MANAGEMENT_VIEW_LIST = PREFIX_ROLE + SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_VIEW = PREFIX_ROLE + SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_VIEW;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_EDIT = PREFIX_ROLE + SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_EDIT;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_CREATE = PREFIX_ROLE + SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_CREATE;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_DELETE = PREFIX_ROLE + SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_DELETE;
	
	public final static String SEC_ROLE_MANAGEMENT = "RM";
	public final static String ROLE_SEC_ROLE_MANAGEMENT_VIEW_LIST = PREFIX_ROLE + SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_SEC_ROLE_MANAGEMENT_VIEW = PREFIX_ROLE + SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_VIEW;
	public final static String ROLE_SEC_ROLE_MANAGEMENT_EDIT = PREFIX_ROLE + SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_EDIT;
	
	//REPORT GENERATOR MENU
	public final static String REPORT_GENERATOR_MENU = "RGM";
	public final static String ROLE_REPORT_GENERATOR_MENU_VIEW = PREFIX_ROLE + REPORT_GENERATOR_MENU + POSTFIX_ACTION_VIEW;
	
	public final static String RPG_REPORT_BUILDER = "RB";
	public final static String ROLE_RPG_REPORT_BUILDER_VIEW_LIST = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_RPG_REPORT_BUILDER_VIEW = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_VIEW;
	public final static String ROLE_RPG_REPORT_BUILDER_EDIT = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_EDIT;
	public final static String ROLE_RPG_REPORT_BUILDER_CREATE = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_CREATE;
	public final static String ROLE_RPG_REPORT_BUILDER_DELETE = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_DELETE;
	public final static String ROLE_RPG_REPORT_BUILDER_SHARING = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_SHARING;
	public final static String ROLE_RPG_REPORT_BUILDER_EXECUTE = PREFIX_ROLE + RPG_REPORT_BUILDER + POSTFIX_ACTION_EXECUTE;
	
	public final static String RPG_REPORT_SCHEDULER = "RS";
	public final static String ROLE_RPG_REPORT_SCHEDULER_VIEW_LIST = PREFIX_ROLE + RPG_REPORT_SCHEDULER + POSTFIX_ACTION_VIEW_LIST;
	public final static String ROLE_RPG_REPORT_SCHEDULER_VIEW = PREFIX_ROLE + RPG_REPORT_SCHEDULER + POSTFIX_ACTION_VIEW;
	public final static String ROLE_RPG_REPORT_SCHEDULER_EDIT = PREFIX_ROLE + RPG_REPORT_SCHEDULER + POSTFIX_ACTION_EDIT;
	public final static String ROLE_RPG_REPORT_SCHEDULER_CREATE = PREFIX_ROLE + RPG_REPORT_SCHEDULER + POSTFIX_ACTION_CREATE;
	public final static String ROLE_RPG_REPORT_SCHEDULER_DELETE = PREFIX_ROLE + RPG_REPORT_SCHEDULER + POSTFIX_ACTION_DELETE;
	
	public final static List<String> ALL_POSSIBLE_ROLES = Arrays.asList(
		ROLE_BASE_MANAGEMENT_MENU_VIEW,
		ROLE_BASE_DB_CONFIG_VIEW_LIST,
		ROLE_BASE_DB_CONFIG_VIEW,
		ROLE_BASE_DB_CONFIG_EDIT,
		ROLE_BASE_DB_CONFIG_CREATE,
		ROLE_BASE_DB_CONFIG_DELETE,
		ROLE_BASE_DB_CONFIG_SHARING,
		ROLE_BASE_TABLE_MAPPING_VIEW_LIST,
		ROLE_BASE_TABLE_MAPPING_VIEW,
		ROLE_BASE_TABLE_MAPPING_EDIT,
		ROLE_BASE_TABLE_MAPPING_CREATE,
		ROLE_BASE_TABLE_MAPPING_SHARING,
		ROLE_BASE_COL_MAPPING_VIEW_LIST,
		ROLE_BASE_COL_MAPPING_VIEW,
		ROLE_BASE_COL_MAPPING_EDIT,
		ROLE_BASE_COL_MAPPING_CREATE,
		ROLE_BASE_COL_MAPPING_SHARING,
		ROLE_SECURITY_MANAGEMENT_MENU_VIEW,
		ROLE_SEC_USER_MANAGEMENT_VIEW_LIST,
		ROLE_SEC_USER_MANAGEMENT_VIEW,
		ROLE_SEC_USER_MANAGEMENT_EDIT,
		ROLE_SEC_USER_MANAGEMENT_CREATE,
		ROLE_SEC_USER_MANAGEMENT_DELETE,
		ROLE_SEC_GROUP_MANAGEMENT_VIEW_LIST,
		ROLE_SEC_GROUP_MANAGEMENT_VIEW,
		ROLE_SEC_GROUP_MANAGEMENT_EDIT,
		ROLE_SEC_GROUP_MANAGEMENT_CREATE,
		ROLE_SEC_GROUP_MANAGEMENT_DELETE,
		ROLE_SEC_ROLE_MANAGEMENT_VIEW_LIST,
		ROLE_SEC_ROLE_MANAGEMENT_VIEW,
		ROLE_SEC_ROLE_MANAGEMENT_EDIT,
		ROLE_REPORT_GENERATOR_MENU_VIEW,
		ROLE_RPG_REPORT_BUILDER_VIEW_LIST,
		ROLE_RPG_REPORT_BUILDER_VIEW,
		ROLE_RPG_REPORT_BUILDER_EDIT,
		ROLE_RPG_REPORT_BUILDER_CREATE,
		ROLE_RPG_REPORT_BUILDER_DELETE,
		ROLE_RPG_REPORT_BUILDER_SHARING,
		ROLE_RPG_REPORT_BUILDER_EXECUTE,
		ROLE_RPG_REPORT_SCHEDULER_VIEW_LIST,
		ROLE_RPG_REPORT_SCHEDULER_VIEW,
		ROLE_RPG_REPORT_SCHEDULER_EDIT,
		ROLE_RPG_REPORT_SCHEDULER_CREATE,
		ROLE_RPG_REPORT_SCHEDULER_DELETE
	);
}
