package com.sharifpro.eurb.info;

public class AuthorityType {
	public final static String MAPPING_MANAGEMENT = "ROLE_MAPPING_MANAGEMENT";
	public final static String MAPPING_MANAGEMENT_DB_LIST = MAPPING_MANAGEMENT + "_DB_LIST";
	public final static String MAPPING_MANAGEMENT_DB = MAPPING_MANAGEMENT + "_DB";
	public final static String MAPPING_MANAGEMENT_TABLE_MAPPING_LIST = MAPPING_MANAGEMENT + "_TABLE_MAP_LIST";
	public final static String MAPPING_MANAGEMENT_TABLE_MAPPING = MAPPING_MANAGEMENT + "_TABLE_MAP";
	public final static String MAPPING_MANAGEMENT_COLUMN_MAPPING_LIST = MAPPING_MANAGEMENT + "_COL_MAP_LIST";
	public final static String MAPPING_MANAGEMENT_COLUMN_MAPPING = MAPPING_MANAGEMENT + "_COL_MAP";
	
	public final static String USER_MANAGEMENT = "ROLE_USER_MANAGEMENT";
	public final static String USER_MANAGEMENT_USER_LIST = USER_MANAGEMENT + "_USER_LIST";
	public final static String USER_MANAGEMENT_USER = USER_MANAGEMENT + "_USER";
	public final static String USER_MANAGEMENT_GROUP_LIST = USER_MANAGEMENT + "_GROUP_LIST";
	public final static String USER_MANAGEMENT_GROUP = USER_MANAGEMENT + "_GROUP";
	public final static String USER_MANAGEMENT_GROUP_MEMBERS_LIST = USER_MANAGEMENT + "_GROUP_MEMBERS_LIST";
	public final static String USER_MANAGEMENT_GROUP_MEMBER = USER_MANAGEMENT + "_GROUP_MEMBER";
	public final static String USER_MANAGEMENT_GROUP_AUTHORITIES_LIST = USER_MANAGEMENT + "_GROUP_AUTHORITIES_LIST";
	public final static String USER_MANAGEMENT_GROUP_AUTHORITY = USER_MANAGEMENT + "_GROUP_AUTHORITY";
	public final static String USER_MANAGEMENT_USER_AUTHORITIES_LIST = USER_MANAGEMENT + "_USER_AUTHORITIES_LIST";
	public final static String USER_MANAGEMENT_USER_AUTHORITY = USER_MANAGEMENT + "_USER_AUTHORITY";
	
	public final static String REPORT_BUILDER = "ROLE_REPORT_BUILDER";
	
	public final static String REPORT_VIEWER = "ROLE_REPORT_VIEWER";
}
