package com.sharifpro.eurb.info;

/**
 * All Authorities in our system
 * 
 * @author Mohammad Dashti (m_dashti [at] ce.sharif.edu)
 */
public class AuthorityType {

	public final static String POSTFIX_ACTION_VIEW = "_R";
	public final static String POSTFIX_ACTION_EDIT = "_W";
	public final static String POSTFIX_ACTION_CREATE = "_C";
	public final static String POSTFIX_ACTION_DELETE = "_D";
	
	public final static String PREFIX_ROLE = "ROLE_";
	
	public final static String USER = PREFIX_ROLE + "USER";
	public final static String ADMIN = PREFIX_ROLE + "ADMIN";
	
	//BASE MENU
	public final static String BASE_MANAGEMENT_MENU = PREFIX_ROLE + "BMM";
	public final static String ROLE_BASE_MANAGEMENT_MENU_VIEW = BASE_MANAGEMENT_MENU + POSTFIX_ACTION_VIEW;
	
	public final static String BASE_DB_CONFIG = PREFIX_ROLE + "DBM";
	public final static String ROLE_BASE_DB_CONFIG_VIEW = BASE_DB_CONFIG + POSTFIX_ACTION_VIEW;
	public final static String ROLE_BASE_DB_CONFIG_EDIT = BASE_DB_CONFIG + POSTFIX_ACTION_EDIT;
	public final static String ROLE_BASE_DB_CONFIG_CREATE = BASE_DB_CONFIG + POSTFIX_ACTION_CREATE;
	public final static String ROLE_BASE_DB_CONFIG_DELETE = BASE_DB_CONFIG + POSTFIX_ACTION_DELETE;
	
	public final static String BASE_TABLE_MAPPING = PREFIX_ROLE + "TM";
	public final static String ROLE_BASE_TABLE_MAPPING_VIEW = BASE_TABLE_MAPPING + POSTFIX_ACTION_VIEW;
	public final static String ROLE_BASE_TABLE_MAPPING_EDIT = BASE_TABLE_MAPPING + POSTFIX_ACTION_EDIT;
	public final static String ROLE_BASE_TABLE_MAPPING_CREATE = BASE_TABLE_MAPPING + POSTFIX_ACTION_CREATE;
	//public final static String ROLE_BASE_TABLE_MAPPING_DELETE = BASE_TABLE_MAPPING + POSTFIX_ACTION_DELETE;
	
	public final static String BASE_COL_MAPPING = PREFIX_ROLE + "CM";
	public final static String ROLE_BASE_COL_MAPPING_VIEW = BASE_COL_MAPPING + POSTFIX_ACTION_VIEW;
	public final static String ROLE_BASE_COL_MAPPING_EDIT = BASE_COL_MAPPING + POSTFIX_ACTION_EDIT;
	public final static String ROLE_BASE_COL_MAPPING_CREATE = BASE_COL_MAPPING + POSTFIX_ACTION_CREATE;
	//public final static String ROLE_BASE_COL_MAPPING_DELETE = BASE_COL_MAPPING + POSTFIX_ACTION_DELETE;
	
	//SECURITY MENU
	public final static String SECURITY_MANAGEMENT_MENU = PREFIX_ROLE + "SMM";
	public final static String ROLE_SECURITY_MANAGEMENT_MENU_VIEW = SECURITY_MANAGEMENT_MENU + POSTFIX_ACTION_VIEW;
	
	public final static String SEC_USER_MANAGEMENT = PREFIX_ROLE + "UM";
	public final static String ROLE_SEC_USER_MANAGEMENT_VIEW = SEC_USER_MANAGEMENT + POSTFIX_ACTION_VIEW;
	public final static String ROLE_SEC_USER_MANAGEMENT_EDIT = SEC_USER_MANAGEMENT + POSTFIX_ACTION_EDIT;
	public final static String ROLE_SEC_USER_MANAGEMENT_CREATE = SEC_USER_MANAGEMENT + POSTFIX_ACTION_CREATE;
	public final static String ROLE_SEC_USER_MANAGEMENT_DELETE = SEC_USER_MANAGEMENT + POSTFIX_ACTION_DELETE;
	
	public final static String SEC_GROUP_MANAGEMENT = PREFIX_ROLE + "GM";
	public final static String ROLE_SEC_GROUP_MANAGEMENT_VIEW = SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_VIEW;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_EDIT = SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_EDIT;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_CREATE = SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_CREATE;
	public final static String ROLE_SEC_GROUP_MANAGEMENT_DELETE = SEC_GROUP_MANAGEMENT + POSTFIX_ACTION_DELETE;
	
	public final static String SEC_ROLE_MANAGEMENT = PREFIX_ROLE + "RM";
	public final static String ROLE_SEC_ROLE_MANAGEMENT_VIEW = SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_VIEW;
	public final static String ROLE_SEC_ROLE_MANAGEMENT_EDIT = SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_EDIT;
	//public final static String ROLE_SEC_ROLE_MANAGEMENT_CREATE = SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_CREATE;
	//public final static String ROLE_SEC_ROLE_MANAGEMENT_DELETE = SEC_ROLE_MANAGEMENT + POSTFIX_ACTION_DELETE;
	
	//REPORT GENERATOR MENU
	public final static String REPORT_GENERATOR_MENU = PREFIX_ROLE + "RGM";
	public final static String ROLE_REPORT_GENERATOR_MENU_VIEW = REPORT_GENERATOR_MENU + POSTFIX_ACTION_VIEW;
	
	public final static String RPG_REPORT_LIST = PREFIX_ROLE + "RL";
	public final static String ROLE_RPG_REPORT_LIST_VIEW = RPG_REPORT_LIST + POSTFIX_ACTION_VIEW;
	//public final static String ROLE_RPG_REPORT_LIST_EDIT = RPG_REPORT_LIST + POSTFIX_ACTION_EDIT;
	//public final static String ROLE_RPG_REPORT_LIST_CREATE = RPG_REPORT_LIST + POSTFIX_ACTION_CREATE;
	//public final static String ROLE_RPG_REPORT_LIST_DELETE = RPG_REPORT_LIST + POSTFIX_ACTION_DELETE;
	
	public final static String RPG_REPORT_BUILDER = PREFIX_ROLE + "RB";
	public final static String ROLE_RPG_REPORT_BUILDER_VIEW = RPG_REPORT_BUILDER + POSTFIX_ACTION_VIEW;
	public final static String ROLE_RPG_REPORT_BUILDER_EDIT = RPG_REPORT_BUILDER + POSTFIX_ACTION_EDIT;
	public final static String ROLE_RPG_REPORT_BUILDER_CREATE = RPG_REPORT_BUILDER + POSTFIX_ACTION_CREATE;
	public final static String ROLE_RPG_REPORT_BUILDER_DELETE = RPG_REPORT_BUILDER + POSTFIX_ACTION_DELETE;
	
	public final static String RPG_REPORT_VIEWER = PREFIX_ROLE + "RV";
	public final static String ROLE_RPG_REPORT_VIEWER_VIEW = RPG_REPORT_VIEWER + POSTFIX_ACTION_VIEW; // TO VIEW THE EXECUTED REPORT
	public final static String ROLE_RPG_REPORT_VIEWER_EDIT = RPG_REPORT_VIEWER + POSTFIX_ACTION_EDIT; // EDIT REPORT AT RUNTIME IF POSSIBLE
	public final static String ROLE_RPG_REPORT_VIEWER_CREATE = RPG_REPORT_VIEWER + POSTFIX_ACTION_CREATE; // TO RUN THE REPORT
	public final static String ROLE_RPG_REPORT_VIEWER_DELETE = RPG_REPORT_VIEWER + POSTFIX_ACTION_DELETE;
	
	public final static String RPG_REPORT_SCHEDULER = PREFIX_ROLE + "RS";
	public final static String ROLE_RPG_REPORT_SCHEDULER_VIEW = RPG_REPORT_SCHEDULER + POSTFIX_ACTION_VIEW;
	public final static String ROLE_RPG_REPORT_SCHEDULER_EDIT = RPG_REPORT_SCHEDULER + POSTFIX_ACTION_EDIT;
	public final static String ROLE_RPG_REPORT_SCHEDULER_CREATE = RPG_REPORT_SCHEDULER + POSTFIX_ACTION_CREATE;
	public final static String ROLE_RPG_REPORT_SCHEDULER_DELETE = RPG_REPORT_SCHEDULER + POSTFIX_ACTION_DELETE;
}
