
package com.sharifpro.matma.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UserInfoService", targetNamespace = "http://ws.matma.sharifpro.com/", wsdlLocation = "http://localhost:8080/eurb/ws/UserInfoService?wsdl")
public class UserInfoService
    extends Service
{

    private final static URL USERINFOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sharifpro.matma.ws.UserInfoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sharifpro.matma.ws.UserInfoService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/eurb/ws/UserInfoService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/eurb/ws/UserInfoService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERINFOSERVICE_WSDL_LOCATION = url;
    }

    public UserInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserInfoService() {
        super(USERINFOSERVICE_WSDL_LOCATION, new QName("http://ws.matma.sharifpro.com/", "UserInfoService"));
    }

    /**
     * 
     * @return
     *     returns UserInfoServiceEndpoint
     */
    @WebEndpoint(name = "UserInfoServiceEndpointPort")
    public UserInfoServiceEndpoint getUserInfoServiceEndpointPort() {
        return super.getPort(new QName("http://ws.matma.sharifpro.com/", "UserInfoServiceEndpointPort"), UserInfoServiceEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserInfoServiceEndpoint
     */
    @WebEndpoint(name = "UserInfoServiceEndpointPort")
    public UserInfoServiceEndpoint getUserInfoServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.matma.sharifpro.com/", "UserInfoServiceEndpointPort"), UserInfoServiceEndpoint.class, features);
    }

}
