package com.sharifpro.eurb.builder.engine.output;

import java.io.Serializable;

/**
 * This object contains the report content generated by the ReportEngine as a
 * btye[] along with additional information decribing the content
 * 
 * @author Erik Swenson
 */

public class ReportEngineOutput implements Serializable
{		
	private static final long serialVersionUID = -1891016289500829002L;
	
	public static final String CONTENT_TYPE_PDF = "application/pdf";
	public static final String CONTENT_TYPE_XLS = "application/vnd.ms-excel";
	public static final String CONTENT_TYPE_HTML = "text/html";
	public static final String CONTENT_TYPE_CSV = "text/comma-separated-values";
	public static final String CONTENT_TYPE_RTF = "application/rtf";
	public static final String CONTENT_TYPE_TEXT = "text/plain";
	public static final String CONTENT_TYPE_XML = "application/xml";
	public static final String CONTENT_TYPE_JPEG = "image/jpeg";
	public static final String CONTENT_TYPE_PNG = "image/png";		
	
	private String contentType;
	private String contentMessage;	
	private byte[] content;			
	
	public byte[] getContent()
	{
		return content;
	}

	public void setContent(byte[] content)
	{
		this.content = content;
	}

	public String getContentType()
	{
		return contentType;
	}

	public void setContentType(String contentType)
	{
		this.contentType = contentType;
	}
	
	public String getContentMessage()
	{
		return contentMessage;
	}

	public void setContentMessage(String contentMessage)
	{
		this.contentMessage = contentMessage;
	}

	public String getContentExtension()
	{	
		if (contentType == null) return "";
		
		if (contentType.equals(CONTENT_TYPE_PDF))
		{
			return ".pdf";
		}
		else if (contentType.equals(CONTENT_TYPE_XLS))
		{
			return ".xls";
		}
		else if (contentType.equals(CONTENT_TYPE_HTML))
		{
			return ".html";
		}
		else if (contentType.equals(CONTENT_TYPE_CSV))
		{
			return ".csv";
		}
		else if (contentType.equals(CONTENT_TYPE_RTF))
		{
			return ".rtf";
		}
		else if (contentType.equals(CONTENT_TYPE_TEXT))
		{
			return ".txt";
		}
		else if (contentType.equals(CONTENT_TYPE_XML))
		{
			return ".xml";
		}
		else if (contentType.equals(CONTENT_TYPE_JPEG))
		{
			return ".jpg";
		}
		else if (contentType.equals(CONTENT_TYPE_PNG))
		{
			return ".png";
		}
		
		return "";
	}
	
	public void setContentExtension(String contentExtension)
	{
		// empty setter
	}
}
